server:
  port: 80

spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: application.log
  level:
    root: error
    com:
      prac:
        monolithic:
          awsmsamonolithicprac:
            config: info
