server:
  port: 80

spring:

  datasource:
    read:
      url:
      username:
      password:
    write:
      url:
      username:
      password:
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
